"""remove type, progress and counter from courses model

Revision ID: ec46516905de
Revises: 
Create Date: 2024-06-08 00:52:27.489377

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'ec46516905de'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('courses', sa.Column('resources', sa.String(length=1024), nullable=False))
    op.drop_column('courses', 'counter')
    op.drop_column('courses', 'progress')
    op.drop_column('courses', 'type')
    op.drop_column('courses', 'link')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('courses', sa.Column('link', mysql.VARCHAR(length=1024), nullable=False))
    op.add_column('courses', sa.Column('type', mysql.VARCHAR(length=256), nullable=False))
    op.add_column('courses', sa.Column('progress', mysql.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('courses', sa.Column('counter', mysql.INTEGER(), autoincrement=False, nullable=False))
    op.drop_column('courses', 'resources')
    # ### end Alembic commands ###
