"""remove counter from task

Revision ID: ecd0c4a6bc3c
Revises: 02e0948e42bd
Create Date: 2024-06-08 04:51:55.010283

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'ecd0c4a6bc3c'
down_revision: Union[str, None] = '02e0948e42bd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tasks', 'counter')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('counter', mysql.INTEGER(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
